"""
"""
import sys
sys.path.append('/home/ubuntu/ercot_virts/time_series')
from feature_ts import stream_mapping


dam_run_streams = [stream_mapping(2632 , 'LoadForecast_South_HZ'),
        stream_mapping(193014 , 'WindActual_South_HZ'),
        stream_mapping(2631 , 'LoadForecast_North_HZ'),
        stream_mapping(192429 , 'WindForecast_North_HZ'), 
        stream_mapping(2633 , 'LoadForecast_West_HZ_aux'),        
        stream_mapping(192423 , 'WindForecast_West_HZ_aux'),
        stream_mapping(2634 , 'LoadForecast_Houston_HZ'),         
        stream_mapping(98214 , 'WindForecast_Houston_HZ'),
        stream_mapping(193022 , 'WindForecast_PAN_HZ'),      
        stream_mapping(159277 , 'SolarForecast_ERCOT'), 
        stream_mapping(224718 , 'ThermalForecast_ERCOT'),           
        stream_mapping(91992, 'DAM_South_HZ_price'),
        stream_mapping(91991, 'DAM_North_HZ_price'),
        stream_mapping(91993, 'DAM_West_HZ_price'),
        stream_mapping(91989, 'DAM_Houston_HZ_price'),
        stream_mapping(242294, 'DAM_PAN_HZ_price'),
        stream_mapping(92003, 'DAM_North_LZ_price'),
        stream_mapping(92005, 'DAM_South_LZ_price'),
        stream_mapping(92006, 'DAM_West_LZ_price'),
        stream_mapping(92001, 'DAM_Houston_LZ_price'),
        stream_mapping(91999, 'DAM_AEN_LZ_price'),
        stream_mapping(92000, 'DAM_CPS_LZ_price'),
        stream_mapping(92002, 'DAM_LCRA_LZ_price'),
        stream_mapping(92004, 'DAM_RAYB_LZ_price'), 
        stream_mapping(279226 , 'North_to_Houston_DAM_Lim'), 
        stream_mapping(198492 , 'East_to_Texas_DAM_Lim'),    
        stream_mapping(299230 , 'Williamson_to_Burnet_DAM_Lim'), 
        stream_mapping(292610 , 'Culberson_DAM_Lim'), 
        stream_mapping(203137 , 'McCamey_DAM_Lim'), 
        stream_mapping(279225 , 'WestTexas_DAM_Lim'), 
        stream_mapping(242385 , 'Nelson_Sharpe_DAM_Lim'), 
        stream_mapping(194385 , 'Nedin_to_Lobo_DAM_Lim'), 
        stream_mapping(242387 , 'Raymondville_to_Riohondo_DAM_Lim'), 
        stream_mapping(279221 , 'Redtap_DAM_Lim'),
        stream_mapping(290391 , 'Valley_Export_DAM_Lim'),
        stream_mapping(290392 , 'Zapata_to_Starr_DAM_Lim'),
        stream_mapping(198152 , 'LoadActual_South_HZ'),
        stream_mapping(193014 , 'WindActual_South_HZ'),
        stream_mapping(198151 , 'LoadActual_North_HZ'),
        stream_mapping(192428 , 'WindActual_North_HZ'), 
        stream_mapping(198153 , 'LoadActual_West_HZ_aux'),        
        stream_mapping(192422 , 'WindActual_West_HZ_aux'),
        stream_mapping(198154 , 'LoadActual_Houston_HZ'),         
        stream_mapping(98213 , 'WindActual_Houston_HZ'),
        stream_mapping(193021 , 'WindActual_PAN_HZ'),      
        stream_mapping(159280 , 'SolarActual_ERCOT'), 
        stream_mapping(224717 , 'ThermalActual_ERCOT', 'HRAVG'),           
        stream_mapping(91992, 'DAM_South_HZ_price'),
        stream_mapping(91991, 'DAM_North_HZ_price'),
        stream_mapping(91993, 'DAM_West_HZ_price'),
        stream_mapping(91989, 'DAM_Houston_HZ_price'),
        stream_mapping(242294, 'DAM_PAN_HZ_price'),
        stream_mapping(92003, 'DAM_North_LZ_price'),
        stream_mapping(92005, 'DAM_South_LZ_price'),
        stream_mapping(92006, 'DAM_West_LZ_price'),
        stream_mapping(92001, 'DAM_Houston_LZ_price'),
        stream_mapping(91999, 'DAM_AEN_LZ_price'),
        stream_mapping(92000, 'DAM_CPS_LZ_price'),
        stream_mapping(92002, 'DAM_LCRA_LZ_price'),
        stream_mapping(92004, 'DAM_RAYB_LZ_price'), 
        stream_mapping(279226 , 'North_to_Houston_DAM_Lim'), 
        stream_mapping(198492 , 'East_to_Texas_DAM_Lim'),    
        stream_mapping(299230 , 'Williamson_to_Burnet_DAM_Lim'), 
        stream_mapping(292610 , 'Culberson_DAM_Lim'), 
        stream_mapping(203137 , 'McCamey_DAM_Lim'), 
        stream_mapping(279225 , 'WestTexas_DAM_Lim'), 
        stream_mapping(242385 , 'Nelson_Sharpe_DAM_Lim'), 
        stream_mapping(194385 , 'Nedin_to_Lobo_DAM_Lim'), 
        stream_mapping(242387 , 'Raymondville_to_Riohondo_DAM_Lim'), 
        stream_mapping(279221 , 'Redtap_DAM_Lim'),
        stream_mapping(290391 , 'Valley_Export_DAM_Lim'),
        stream_mapping(290392 , 'Zapata_to_Starr_DAM_Lim'),
        stream_mapping(91991, 'DAM_North_HZ_price'),
        stream_mapping(91992, 'DAM_South_HZ_price'),
        stream_mapping(91993, 'DAM_West_HZ_price'),
        stream_mapping(91989, 'DAM_Houston_HZ_price'),
        stream_mapping(242294, 'DAM_PAN_HZ_price'),
        stream_mapping(92003, 'DAM_North_LZ_price'),
        stream_mapping(92005, 'DAM_South_LZ_price'),
        stream_mapping(92006, 'DAM_West_LZ_price'),
        stream_mapping(92001, 'DAM_Houston_LZ_price'),
        stream_mapping(91999, 'DAM_AEN_LZ_price'),
        stream_mapping(92000, 'DAM_CPS_LZ_price'),
        stream_mapping(92002, 'DAM_LCRA_LZ_price'),
        stream_mapping(92004, 'DAM_RAYB_LZ_price'),
        stream_mapping(2632 , 'LoadForecast_South_HZ'),
        stream_mapping(193014 , 'WindForecast_South_HZ'),
        stream_mapping(2631 , 'LoadForecast_North_HZ'),
        stream_mapping(192429 , 'WindForecast_North_HZ'),
        stream_mapping(2633 , 'LoadForecast_West_HZ_aux'),        
        stream_mapping(192423 , 'WindForecast_West_HZ_aux'),
        stream_mapping(2634 , 'LoadForecast_Houston_HZ'),        
        stream_mapping(98214 , 'WindForecast_Houston_HZ'),
        stream_mapping(193022 , 'WindForecast_PAN_HZ'),
        stream_mapping(159277 , 'SolarForecast_ERCOT'),
        stream_mapping(279226 , 'North_to_Houston_DAM_Lim'), 
        stream_mapping(198492 , 'East_to_Texas_DAM_Lim'), 
        #stream_mapping(279223 , 'Bearkat_DAM_Lim'), 
        stream_mapping(299230 , 'Williamson_to_Burnet_DAM_Lim'), 
        stream_mapping(292610 , 'Culberson_DAM_Lim'), 
        stream_mapping(203137 , 'McCamey_DAM_Lim'), 
        stream_mapping(279225 , 'WestTexas_DAM_Lim'), 
        stream_mapping(242385 , 'Nelson_Sharpe_DAM_Lim'), 
        stream_mapping(194385 , 'Nedin_to_Lobo_DAM_Lim'), 
        stream_mapping(242387 , 'Raymondville_to_Riohondo_DAM_Lim'), 
        stream_mapping(279221 , 'Redtap_DAM_Lim'),
        stream_mapping(290391 , 'Valley_Export_DAM_Lim'),
        stream_mapping(290392 , 'Zapata_to_Starr_DAM_Lim'),
        stream_mapping(2632 , 'LoadForecast_South_HZ'),
        stream_mapping(91991, 'DAM_North_HZ_price'),
        stream_mapping(91992, 'DAM_South_HZ_price'),
        stream_mapping(91993, 'DAM_West_HZ_price'),
        stream_mapping(91989, 'DAM_Houston_HZ_price'),
        stream_mapping(242294, 'DAM_PAN_HZ_price'),
        stream_mapping(92003, 'DAM_North_LZ_price'),
        stream_mapping(92005, 'DAM_South_LZ_price'),
        stream_mapping(92006, 'DAM_West_LZ_price'),
        stream_mapping(92001, 'DAM_Houston_LZ_price'),
        stream_mapping(91999, 'DAM_AEN_LZ_price'),
        stream_mapping(92000, 'DAM_CPS_LZ_price'),
        stream_mapping(92002, 'DAM_LCRA_LZ_price'),
        stream_mapping(92004, 'DAM_RAYB_LZ_price')]

rtm_run_streams = [
    stream_mapping(91407, "Settle_North_HZ_price"),
    stream_mapping(91408, "Settle_South_HZ_price"),
    stream_mapping(91409, "Settle_West_HZ_price"),
    stream_mapping(91405, "Settle_Houston_HZ_price"),
    stream_mapping(242293, "Settle_PAN_HZ_price"),
    stream_mapping(91419, "Settle_North_LZ_price"),
    stream_mapping(91421, "Settle_South_LZ_price"),
    stream_mapping(91422, "Settle_West_LZ_price"),
    stream_mapping(91417, "Settle_Houston_LZ_price"),
    stream_mapping(91415, "Settle_AEN_LZ_price"),
    stream_mapping(91416, "Settle_CPS_LZ_price"),
    stream_mapping(91418, "Settle_LCRA_LZ_price"),
    stream_mapping(91420, "Settle_RAYB_LZ_price"),
    stream_mapping(85015, "LoadForecast_South_HZ"),
    stream_mapping(85013, "LoadForecast_Total_HZ"),
    stream_mapping(112410, "WindForecast_South_HZ"),
    stream_mapping(85014, "LoadForecast_North_HZ"),
    stream_mapping(192435, "WindForecast_North_HZ"),
    stream_mapping(85016, "LoadForecast_West_HZ_aux"),
    stream_mapping(192434, "WindForecast_West_HZ_aux"),
    stream_mapping(85017, "LoadForecast_Houston_HZ"),
    stream_mapping(112410, "WindForecast_Houston_HZ"),
    stream_mapping(193022, "WindForecast_PAN_HZ"), #NOTE: No 9am snapshot available
    stream_mapping(278172, "SolarForecast_ERCOT"),
    stream_mapping(91991, "DAM_North_HZ_price"),
    stream_mapping(91992, "DAM_South_HZ_price"),
    stream_mapping(91993, "DAM_West_HZ_price"),
    stream_mapping(91989, "DAM_Houston_HZ_price"),
    stream_mapping(224718, "ThermalForecast_ERCOT"),
    stream_mapping(242294, "DAM_PAN_HZ_price"),
    stream_mapping(92003, "DAM_North_LZ_price"),
    stream_mapping(92005, "DAM_South_LZ_price"),
    stream_mapping(92006, "DAM_West_LZ_price"),
    stream_mapping(92001, "DAM_Houston_LZ_price"),
    stream_mapping(91999, "DAM_AEN_LZ_price"),
    stream_mapping(92000, "DAM_CPS_LZ_price"),
    stream_mapping(92002, "DAM_LCRA_LZ_price"),
    stream_mapping(92004, "DAM_RAYB_LZ_price"),
    stream_mapping(198152, "LoadActual_South_HZ"),
    stream_mapping(193014, "WindActual_South_HZ"),
    stream_mapping(198151, "LoadActual_North_HZ"),
    stream_mapping(192428, "WindActual_North_HZ"),
    stream_mapping(198153, "LoadActual_West_HZ_aux"),
    stream_mapping(192422, "WindActual_West_HZ_aux"),
    stream_mapping(198154, "LoadActual_Houston_HZ"),
    stream_mapping(98213, "WindActual_Houston_HZ"),
    stream_mapping(193021, "WindActual_PAN_HZ"),
    stream_mapping(159280, "SolarActual_ERCOT"),
    stream_mapping(224717, "ThermalActual_ERCOT", "HRAVG"),
    stream_mapping(279226, "North_to_Houston_DAM_Lim"),
    stream_mapping(198492, "East_to_Texas_DAM_Lim"),
    stream_mapping(299230, "Williamson_to_Burnet_DAM_Lim"),
    stream_mapping(292610, "Culberson_DAM_Lim"),
    stream_mapping(203137, "McCamey_DAM_Lim"),
    stream_mapping(279225, "WestTexas_DAM_Lim"),
    stream_mapping(242385, "Nelson_Sharpe_DAM_Lim"),
    stream_mapping(194385, "Nedin_to_Lobo_DAM_Lim"),
    stream_mapping(242387, "Raymondville_to_Riohondo_DAM_Lim"),
    stream_mapping(279221, "Redtap_DAM_Lim"),
    stream_mapping(290391, "Valley_Export_DAM_Lim"),
    stream_mapping(290392, "Zapata_to_Starr_DAM_Lim"),
    stream_mapping(244605, 'wind_pct_output'),
    stream_mapping(244603, 'wind_icap'), #installed wind capacity
    stream_mapping(322662, 'solar_icap'), #installed solar capacity
]


five_min_streams = [        stream_mapping(2632 , 'LoadForecast_South_HZ'),
        stream_mapping(92594, 'RTM_North_HZ_price'),
        stream_mapping(92595, 'RTM_South_HZ_price'),
        stream_mapping(92596, 'RTM_West_HZ_price'),
        stream_mapping(92592, 'RTM_Houston_HZ_price'),
        stream_mapping(242292, 'RTM_PAN_HZ_price'),
        stream_mapping(92606, 'RTM_North_LZ_price'),
        stream_mapping(92608, 'RTM_South_LZ_price'),
        stream_mapping(92609, 'RTM_West_LZ_price'),
        stream_mapping(92604, 'RTM_Houston_LZ_price'),
        stream_mapping(92602, 'RTM_AEN_LZ_price'),
        stream_mapping(92603, 'RTM_CPS_LZ_price'),
        stream_mapping(92605, 'RTM_LCRA_LZ_price'),
        stream_mapping(92607, 'RTM_RAYB_LZ_price'), 
]
